### ISSUE TITLE
not correct price for game DARK SOULS™ II: Scholar of the First Sin

### ISSUE THREAD

**Issue by vzhik227** [SteamDatabase/steamdb.info#476] opened 2017-02-21 17:14 UTC
Hi. I noticed the price incorrectly.
for example  game DARK SOULS™ II  of the value  is displayed correctly
http://i90.fastpic.ru/big/2017/0221/74/ec26c3d3ee83344ae54982d4a8384174.jpg
1199p  on the site = 1199p on steam.  This is price for the my country Russian Federation.
but for the game DARK SOULS™ II: Scholar of the First Sin price is displayed is not correctly.
http://i91.fastpic.ru/big/2017/0221/e1/47a2146bd0af15970fceaf5cee0815e1.jpg
499p on site and 1199p on steam.
I know why there is such a price. This price is available only if you already have  the DARK SOULS ™II  in steam library . This price for the upgrade DARK SOULS ™II  to DARK SOULS™ II: Scholar of the First Sin. Full price for the buy 1199p.
http://i91.fastpic.ru/big/2017/0221/c5/a97f75d8fe095e59fc2d5d80244777c5.jpg

**Comment by xPaw** [comment] 2017-03-10 16:28
Duplicate of #463

**Closed by xPaw** 2017-03-10 16:28 UTC

**Comment by xPaw** [comment] 2017-10-06 11:50
This is fixed now.
