### ISSUE TITLE
Dark Souls II SotFS "incorrect" price

### ISSUE THREAD

**Issue by Psycheage** [SteamDatabase/steamdb.info#502] opened 2017-07-05 21:39 UTC
SteamDB lists Dark Souls II SotFS as being $29.99 when that is really just the upgrade price while the "real" price is $39.99. I assume this has happened because the automatic process takes the lowest current price on the store and uses that. I don't know if this is that big of a deal to you but I just wanna let people know.

**Comment by xPaw** [comment] 2017-07-05 21:41
Duplicate of #463.

**Closed by xPaw** 2017-07-05 21:41 UTC

**Comment by xPaw** [comment] 2017-10-06 11:51
This is fixed now.
